pcd2pgm:
  ros__parameters:
    pcd_file: /home/akun/Desktop/map1/GlobalMap.pcd
    odom_to_lidar_odom: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # odom_to_lidar_odom: [-0.16, 0.0, -0.18, -0.523599, 0.0, -1.5707963]
    flag_pass_through: false # 如果设置成false，保留在thre_z_max和thre_z_min之间的点（带通）。如果设置成true，则保留大于thre_z_max和小于thre_z_min的点（带阻）。
    map_resolution: 0.1
    map_topic_name: map
    thre_radius: 0.5
    thre_z_max: 1.0
    thre_z_min: -3.0
    thres_point_count: 10
